--------------------------------------------------------
-- Archivo creado  - lunes-noviembre-11-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Procedure PR_UPDATE_SALDO_CREDITO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FACIS"."PR_UPDATE_SALDO_CREDITO" 
(
  P_K_NUMCONSIGNACION IN PAGO.K_NUMCONSIGNACION%TYPE
) AS
-- PROCEDIMIENTO QUE ACTUALIZA EL SALDO DE UN CREDITO
-- ESTE PROCEDIMIENTO SE LLAMA CADA VEZ QUE SE REALIZA EL PAGO A UN CREDITO

  L_K_ID_CREDITO CREDITO.K_ID_CREDITO%TYPE;
  L_V_CAPITAL PLANPAGOS.V_XCAPITAL%TYPE;
  
BEGIN

  SELECT PP.K_ID_CREDITO
  INTO  L_K_ID_CREDITO
  FROM PLANPAGOS PP, PAGO P 
  WHERE PP.K_ID_PLAN = P.K_ID_PLAN
  AND   P.K_NUMCONSIGNACION = P_K_NUMCONSIGNACION;
  
  SELECT SUM(PP.V_XCAPITAL)
  INTO L_V_CAPITAL
  FROM PLANPAGOS PP, PAGO P
  WHERE PP.K_ID_PLAN = P.K_ID_PLAN
  AND   PP.K_ID_CREDITO = L_K_ID_CREDITO;

  UPDATE CREDITO C
  SET V_SALDO = V_CREDITO - L_V_CAPITAL
  WHERE K_ID_CREDITO = L_K_ID_CREDITO;
  
  COMMIT;

END PR_UPDATE_SALDO_CREDITO;

/
