--CREANDO TABLESPACE PARA FACIS

CREATE TABLESPACE facis DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\FACIS.DBF' SIZE 1M AUTOEXTEND ON;
CREATE TEMPORARY TABLESPACE tempfacis TEMPFILE 'C:\oraclexe\app\oracle\oradata\XE\TEMFACIS.DBF' SIZE 5M AUTOEXTEND ON;

--CREACION DE USUARIO FACIS

DROP USER facis CASCADE;

CREATE USER facis IDENTIFIED BY facis 
DEFAULT TABLESPACE facis
TEMPORARY TABLESPACE tempfacis
QUOTA UNLIMITED ON facis;

GRANT CONNECT,RESOURCE,DBA TO facis;