--CREANDO SINONIMOS

DROP PUBLIC SYNONYM SOCIO;
DROP PUBLIC SYNONYM TIPO_CREDITO;
DROP PUBLIC SYNONYM RENDIMIENTO;
DROP PUBLIC SYNONYM PLANPAGOS;
DROP PUBLIC SYNONYM PAGO;
DROP PUBLIC SYNONYM GANANCIARENDIMIENTO;
DROP PUBLIC SYNONYM GANANCIA;
DROP PUBLIC SYNONYM FORMAPAGO;
DROP PUBLIC SYNONYM DESCRIPCIONAPORTE;
DROP PUBLIC SYNONYM DESCRIPCION_TIPO_CREDITO;
DROP PUBLIC SYNONYM CUENTA;
DROP PUBLIC SYNONYM CREDITO;
DROP PUBLIC SYNONYM APORTE;

CREATE PUBLIC SYNONYM SOCIO FOR FACIS.SOCIO;
CREATE PUBLIC SYNONYM TIPO_CREDITO FOR FACIS.TIPO_CREDITO;
CREATE PUBLIC SYNONYM RENDIMIENTO FOR FACIS.RENDIMIENTO;
CREATE PUBLIC SYNONYM PLANPAGOS FOR FACIS.PLANPAGOS;
CREATE PUBLIC SYNONYM PAGO FOR FACIS.PAGO;
CREATE PUBLIC SYNONYM GANANCIARENDIMIENTO FOR FACIS.GANANCIARENDIMIENTO;
CREATE PUBLIC SYNONYM GANANCIA FOR FACIS.GANANCIA;
CREATE PUBLIC SYNONYM FORMAPAGO FOR FACIS.FORMAPAGO;
CREATE PUBLIC SYNONYM DESCRIPCIONAPORTE FOR FACIS.DESCRIPCIONAPORTE;
CREATE PUBLIC SYNONYM DESCRIPCION_TIPO_CREDITO FOR FACIS.DESCRIPCION_TIPO_CREDITO;
CREATE PUBLIC SYNONYM CUENTA FOR FACIS.CUENTA;
CREATE PUBLIC SYNONYM CREDITO FOR FACIS.CREDITO;
CREATE PUBLIC SYNONYM APORTE FOR FACIS.APORTE;